-- Generated by Oracle SQL Developer Data Modeler 4.1.3.901
--   at:        2017-11-30 14:26:04 COT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




CREATE TABLE AcuerdoPago
  (
    idAcuerdoPago     INTEGER NOT NULL ,
    fechaAcuerdo      DATE NOT NULL ,
    idBanco           INTEGER ,
    idGrupoFin        INTEGER ,
    idTipoTarjeta     INTEGER ,
    idModalidadDePago INTEGER NOT NULL ,
    idCotizacion      INTEGER NOT NULL ,
    porcentaje        INTEGER NOT NULL ,
    valor             NUMBER (11,3) NOT NULL ,
    parpct            NUMBER (2) NOT NULL ,
    valido            VARCHAR2 (2 CHAR) NOT NULL
  ) ;
ALTER TABLE AcuerdoPago ADD CONSTRAINT AcuerdoPago_PK PRIMARY KEY ( idAcuerdoPago, idCotizacion ) ;


CREATE TABLE Aseguradora
  (
    idAseguradora     INTEGER NOT NULL ,
    nombreAseguradora VARCHAR2 (25 CHAR) NOT NULL ,
    costoSeguro       INTEGER NOT NULL
  ) ;
ALTER TABLE Aseguradora ADD CONSTRAINT Aseguradora_PK PRIMARY KEY ( idAseguradora ) ;


CREATE TABLE AsistenteCapacitacion
  (
    idAsistente     INTEGER NOT NULL ,
    nombreAsistente VARCHAR2 (30 CHAR) NOT NULL ,
    opinion         VARCHAR2 (50 CHAR)
  ) ;
ALTER TABLE AsistenteCapacitacion ADD CONSTRAINT AsistenteCapacitacion_PK PRIMARY KEY ( idAsistente ) ;


CREATE TABLE Auto
  (
    vim           INTEGER NOT NULL ,
    fechaEnsamble DATE NOT NULL ,
    nombreAuto    VARCHAR2 (50 CHAR)
  ) ;
ALTER TABLE Auto ADD CONSTRAINT Auto_PK PRIMARY KEY ( vim ) ;


CREATE TABLE AutoCaracteristica
  (
    descAutoCarac    VARCHAR2 (25 CHAR) ,
    idAuto           INTEGER NOT NULL ,
    idCaracteristica INTEGER NOT NULL
  ) ;
ALTER TABLE AutoCaracteristica ADD CONSTRAINT AutoCaracteristica_PK PRIMARY KEY ( idAuto, idCaracteristica ) ;


CREATE TABLE Banco
  (
    idBanco     INTEGER NOT NULL ,
    nombreBanco VARCHAR2 (25 CHAR) NOT NULL ,
    correoBanco VARCHAR2 (50 CHAR) NOT NULL
  ) ;
ALTER TABLE Banco ADD CONSTRAINT Banco_PK PRIMARY KEY ( idBanco ) ;


CREATE TABLE Capacitacion
  (
    idCapacitacion     INTEGER NOT NULL ,
    nombreCap          VARCHAR2 (25 CHAR) NOT NULL ,
    temaCap            VARCHAR2 (25 CHAR) NOT NULL ,
    resultadosCap      VARCHAR2 (25 CHAR) NOT NULL ,
    cantidadAsistentes INTEGER NOT NULL ,
    duracion           INTEGER NOT NULL ,
    fechaCap           DATE NOT NULL ,
    idCapacitador      INTEGER ,
    dAsistente         INTEGER NOT NULL
  ) ;
ALTER TABLE Capacitacion ADD CONSTRAINT Capacitacion_PK PRIMARY KEY ( idCapacitacion ) ;


CREATE TABLE Caracteristica
  (
    idCarac             INTEGER NOT NULL ,
    descrCaracteristica VARCHAR2 (25 CHAR) ,
    idTipoCarac         INTEGER NOT NULL ,
    idCaracPadre        INTEGER
  ) ;
ALTER TABLE Caracteristica ADD CONSTRAINT Caracteristica_PK PRIMARY KEY ( idCarac ) ;
ALTER TABLE Caracteristica ADD CONSTRAINT Carac_idCarac_UN UNIQUE ( idCarac ) ;


CREATE TABLE Cargo
  (
    idCargo     INTEGER NOT NULL ,
    nombreCargo VARCHAR2 (30 CHAR) NOT NULL
  ) ;
ALTER TABLE Cargo ADD CONSTRAINT Cargo_PK PRIMARY KEY ( idCargo ) ;


CREATE TABLE Cliente
  (
    idCliente         INTEGER NOT NULL ,
    primerNombre      VARCHAR2 (25 CHAR) NOT NULL ,
    primerApellido    VARCHAR2 (25 CHAR) NOT NULL ,
    segundoNombre     VARCHAR2 (25 CHAR) ,
    segundoApellido   VARCHAR2 (25 CHAR) ,
    fechaDeNacimiento DATE NOT NULL
  ) ;
ALTER TABLE Cliente ADD CONSTRAINT Cliente_PK PRIMARY KEY ( idCliente ) ;


CREATE TABLE Contacto
  (
    idContacto          INTEGER NOT NULL ,
    descripcionContacto VARCHAR2 (25 CHAR) NOT NULL ,
    idTipoContacto      INTEGER NOT NULL ,
    idCliente           INTEGER NOT NULL
  ) ;
ALTER TABLE Contacto ADD CONSTRAINT Contacto_PK PRIMARY KEY ( idContacto ) ;


CREATE TABLE Cotizacion
  (
    idCotizacion    INTEGER NOT NULL ,
    fechaCotizacion DATE NOT NULL ,
    vigencia        INTEGER NOT NULL ,
    idCliente       INTEGER NOT NULL ,
    idEmpleado      INTEGER NOT NULL ,
    totalCotizacion NUMBER (11,3)
  ) ;
ALTER TABLE Cotizacion ADD CONSTRAINT Cotizacion_PK PRIMARY KEY ( idCotizacion ) ;


CREATE TABLE DescuentoPago
  (
    idDescuentoPago INTEGER NOT NULL ,
    valor           INTEGER NOT NULL ,
    idTipoDescuento INTEGER NOT NULL ,
    idPagoEmpleado  INTEGER NOT NULL
  ) ;
ALTER TABLE DescuentoPago ADD CONSTRAINT DescuentoPago_PK PRIMARY KEY ( idPagoEmpleado, idDescuentoPago ) ;


CREATE TABLE DetalleCotizacion
  (
    idDetalleCotizacion INTEGER NOT NULL ,
    descCotizacion      VARCHAR2 (25 CHAR) NOT NULL ,
    idCotizacion        INTEGER NOT NULL ,
    elemento            INTEGER NOT NULL ,
    valorElemento       NUMBER (11,3) NOT NULL ,
    nombreDetalle       VARCHAR2 (50 CHAR)
  ) ;
ALTER TABLE DetalleCotizacion ADD CONSTRAINT DetalleCotizacion_PK PRIMARY KEY ( idDetalleCotizacion, idCotizacion ) ;


CREATE TABLE DetalleFactura
  (
    idDetalleFact  INTEGER NOT NULL ,
    desDetalleFact VARCHAR2 (25 CHAR) ,
    idFactura      INTEGER NOT NULL ,
    idAcuerdoPago  INTEGER ,
    idCotizacion   INTEGER ,
    valorDetalle   NUMBER (11,3) NOT NULL
  ) ;
CREATE UNIQUE INDEX DetalleFactura__IDX ON DetalleFactura
  (
    idAcuerdoPago ASC , idCotizacion ASC
  )
  ;
ALTER TABLE DetalleFactura ADD CONSTRAINT DetalleFactura_PK PRIMARY KEY ( idDetalleFact, idFactura ) ;


CREATE TABLE Empleado
  (
    idEmpleado       INTEGER NOT NULL ,
    nombreEmpleado   VARCHAR2 (25 CHAR) NOT NULL ,
    ApellidoEmpleado VARCHAR2 (25 CHAR) NOT NULL ,
    fechaInicio      DATE NOT NULL ,
    fechaFin         DATE NOT NULL ,
    salarioBase      INTEGER NOT NULL ,
    idEvaluador      INTEGER ,
    idCargo          INTEGER NOT NULL ,
    idRegion         INTEGER NOT NULL ,
    usuario          VARCHAR2 (50 CHAR) NOT NULL
  ) ;
CREATE UNIQUE INDEX Empleado__IDX ON Empleado
  (
    idEvaluador ASC
  )
  ;
ALTER TABLE Empleado ADD CONSTRAINT Empleado_PK PRIMARY KEY ( idEmpleado ) ;


CREATE TABLE EstadoStock
  (
    idEstadoStock   INTEGER NOT NULL ,
    descEstadoStock VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE EstadoStock ADD CONSTRAINT EstadoStock_PK PRIMARY KEY ( idEstadoStock ) ;


CREATE TABLE EstadoStockParte
  (
    idEstadoStockParte   INTEGER NOT NULL ,
    DescEstadoStockParte VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE EstadoStockParte ADD CONSTRAINT EstadoStockParte_PK PRIMARY KEY ( idEstadoStockParte ) ;


CREATE TABLE Evaluacion
  (
    idEvaluacion    INTEGER NOT NULL ,
    calificacion    INTEGER NOT NULL ,
    justificacion   VARCHAR2 (25 CHAR) NOT NULL ,
    fechaEvaluacion DATE NOT NULL
  ) ;
ALTER TABLE Evaluacion ADD CONSTRAINT Evaluacion_PK PRIMARY KEY ( idEvaluacion ) ;


CREATE TABLE Factura
  (
    idFactura      INTEGER NOT NULL ,
    fechaFacturado DATE NOT NULL ,
    idCotizacion   INTEGER NOT NULL ,
    idCliente      INTEGER ,
    idTipoFactura  INTEGER NOT NULL ,
    idEmpleado     INTEGER NOT NULL ,
    idProveedor    INTEGER ,
    totalFactura   NUMBER (11,3)
  ) ;
ALTER TABLE Factura ADD CONSTRAINT Factura_PK PRIMARY KEY ( idFactura ) ;


CREATE TABLE Garantia
  (
    idGarantia          INTEGER NOT NULL ,
    fechaGarantia       DATE NOT NULL ,
    Registro_idRegistro INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX Garantia__IDX ON Garantia
  (
    Registro_idRegistro ASC
  )
  ;
ALTER TABLE Garantia ADD CONSTRAINT Garantia_PK PRIMARY KEY ( idGarantia ) ;


CREATE TABLE GrupoFinanciero
  (
    idGrupo               INTEGER NOT NULL ,
    nombreGrupoFinanciero VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE GrupoFinanciero ADD CONSTRAINT GrupoFinanciero_PK PRIMARY KEY ( idGrupo ) ;


CREATE TABLE HistoPrecioParte
  (
    idHistoPreParte           INTEGER NOT NULL ,
    descripcionHistoricoParte VARCHAR2 (25 CHAR) NOT NULL ,
    idParte                   INTEGER NOT NULL ,
    precioParte               NUMBER (11,3) NOT NULL ,
    fechaPrecioParte          DATE NOT NULL
  ) ;
ALTER TABLE HistoPrecioParte ADD CONSTRAINT HistoricoPrecioParte_PK PRIMARY KEY ( idHistoPreParte ) ;


CREATE TABLE HistoPreciosAuto
  (
    idHistoPreciosAuto INTEGER NOT NULL ,
    descHistoPreAuto   VARCHAR2 (50 CHAR) NOT NULL ,
    fechaPrecioAuto    DATE NOT NULL ,
    idAuto             INTEGER NOT NULL ,
    precioAuto         NUMBER (11,3) NOT NULL
  ) ;
ALTER TABLE HistoPreciosAuto ADD CONSTRAINT HistoricoPreciosAuto_PK PRIMARY KEY ( idHistoPreciosAuto ) ;


CREATE TABLE HistoricoPreciosReg
  (
    idHistoricoPreciosReg INTEGER NOT NULL ,
    descripcionHistReg    VARCHAR2 (50 CHAR) NOT NULL ,
    idRegistro            INTEGER NOT NULL ,
    precioReg             NUMBER (11,3) NOT NULL
  ) ;
ALTER TABLE HistoricoPreciosReg ADD CONSTRAINT HistoricoPreciosReg_PK PRIMARY KEY ( idHistoricoPreciosReg ) ;


CREATE TABLE ModalidadDePago
  (
    idModalidad          INTEGER NOT NULL ,
    nombreModalidad      VARCHAR2 (25 CHAR) ,
    descripcionModalidad VARCHAR2 (25 CHAR)
  ) ;
ALTER TABLE ModalidadDePago ADD CONSTRAINT ModalidadDePago_PK PRIMARY KEY ( idModalidad ) ;


CREATE TABLE PagoEmpleado
  (
    idPagoEmpleado   INTEGER NOT NULL ,
    fechaPagoSalario DATE NOT NULL ,
    pagoTotal        INTEGER NOT NULL ,
    idEmpleado       INTEGER NOT NULL
  ) ;
ALTER TABLE PagoEmpleado ADD CONSTRAINT PagoEmpleado_PK PRIMARY KEY ( idPagoEmpleado ) ;


CREATE TABLE Parte
  (
    idParte          INTEGER NOT NULL ,
    nombreParte      VARCHAR2 (25 CHAR) NOT NULL ,
    descripcionParte VARCHAR2 (25 CHAR) ,
    idTipoParte      INTEGER NOT NULL
  ) ;
ALTER TABLE Parte ADD CONSTRAINT Parte_PK PRIMARY KEY ( idParte ) ;


CREATE TABLE ParteAuto
  (
    idParteAuto          INTEGER NOT NULL ,
    descripcionParteAuto VARCHAR2 (25 CHAR) NOT NULL ,
    idAuto               INTEGER NOT NULL ,
    idParte              INTEGER NOT NULL ,
    precioParteAuto      NUMBER (11,3) NOT NULL
  ) ;
ALTER TABLE ParteAuto ADD CONSTRAINT ParteAuto_PK PRIMARY KEY ( idParteAuto ) ;


CREATE TABLE Proceso
  (
    idProceso          INTEGER NOT NULL ,
    descripcionProceso VARCHAR2 (25 CHAR) NOT NULL ,
    idTipoProceso      INTEGER NOT NULL ,
    idCotizacion       INTEGER NOT NULL ,
    fechaProceso       DATE NOT NULL ,
    activo             VARCHAR2 (50 CHAR) NOT NULL
  ) ;
ALTER TABLE Proceso ADD CONSTRAINT Proceso_PK PRIMARY KEY ( idProceso ) ;


CREATE TABLE Proveedor
  (
    idProveedor     INTEGER NOT NULL ,
    nombreProveedor VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE Proveedor ADD CONSTRAINT Proveedor_PK PRIMARY KEY ( idProveedor ) ;


CREATE TABLE RecursoOficina
  (
    idRecurso          INTEGER NOT NULL ,
    estadoRecurso      VARCHAR2 (25 CHAR) NOT NULL ,
    nombreRecurso      VARCHAR2 (25 CHAR) NOT NULL ,
    descripcionRecurso VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE RecursoOficina ADD CONSTRAINT RecursoOficina_PK PRIMARY KEY ( idRecurso ) ;


CREATE TABLE Region
  (
    idRegion     INTEGER NOT NULL ,
    nombreRegion VARCHAR2 (30 CHAR) NOT NULL
  ) ;
ALTER TABLE Region ADD CONSTRAINT Region_PK PRIMARY KEY ( idRegion ) ;


CREATE TABLE Registro
  (
    idRegistro          INTEGER NOT NULL ,
    descripcionRegistro VARCHAR2 (25 CHAR) ,
    idTipoRegistro      INTEGER NOT NULL ,
    idAseguradora       INTEGER ,
    idCotizacion        INTEGER NOT NULL ,
    idMensajero         INTEGER ,
    idAsesor            INTEGER NOT NULL
  ) ;
ALTER TABLE Registro ADD CONSTRAINT Registro_PK PRIMARY KEY ( idRegistro ) ;


CREATE TABLE RespRecursoOfi
  (
    idResponsable   INTEGER NOT NULL ,
    fechaAsignacion DATE NOT NULL ,
    fechaRetorno    DATE NOT NULL ,
    idEmpleado      INTEGER NOT NULL ,
    idRecurso       INTEGER NOT NULL
  ) ;
ALTER TABLE RespRecursoOfi ADD CONSTRAINT ResponeRecursoOfi_PK PRIMARY KEY ( idResponsable, idEmpleado, idRecurso ) ;


CREATE TABLE StockAutos
  (
    idStockAutos      INTEGER NOT NULL ,
    cantidad          INTEGER NOT NULL ,
    idDetalleFactura  INTEGER NOT NULL ,
    idDocRespaldo     INTEGER NOT NULL ,
    idTipoMovimientos INTEGER NOT NULL ,
    idAuto            INTEGER NOT NULL ,
    idEstadoStock     INTEGER NOT NULL
  ) ;
ALTER TABLE StockAutos ADD CONSTRAINT StockAutos_PK PRIMARY KEY ( idStockAutos ) ;


CREATE TABLE StockParte
  (
    idStockParte       INTEGER NOT NULL ,
    cantidadPartes     INTEGER NOT NULL ,
    idDetalleFactura   INTEGER NOT NULL ,
    idFactura          INTEGER NOT NULL ,
    idTipoMovimientos  INTEGER NOT NULL ,
    idParte            INTEGER NOT NULL ,
    idEstadoStockParte INTEGER NOT NULL
  ) ;
ALTER TABLE StockParte ADD CONSTRAINT StockParte_PK PRIMARY KEY ( idStockParte ) ;


CREATE TABLE TIpoRegistro
  (
    idTipoRegistro     INTEGER NOT NULL ,
    descripcionTipoReg VARCHAR2 (50 CHAR) NOT NULL
  ) ;
ALTER TABLE TIpoRegistro ADD CONSTRAINT TIpoRegistro_PK PRIMARY KEY ( idTipoRegistro ) ;


CREATE TABLE TipoCaracteristica
  (
    idTipoCaracteristica INTEGER NOT NULL ,
    nombreTipoCarac      VARCHAR2 (30 CHAR) NOT NULL
  ) ;
ALTER TABLE TipoCaracteristica ADD CONSTRAINT TipoCaracteristica_PK PRIMARY KEY ( idTipoCaracteristica ) ;


CREATE TABLE TipoContacto
  (
    idTipoContacto      INTEGER NOT NULL ,
    nombreTipoCont      VARCHAR2 (25 CHAR) NOT NULL ,
    descripcionTipoCont VARCHAR2 (25 CHAR)
  ) ;
ALTER TABLE TipoContacto ADD CONSTRAINT TipoContacto_PK PRIMARY KEY ( idTipoContacto ) ;


CREATE TABLE TipoDescuentoNomina
  (
    idTipoDesc          INTEGER NOT NULL ,
    nombreTipoDescuento VARCHAR2 (25 CHAR) NOT NULL ,
    porcentajeTipoDescuento FLOAT (2) NOT NULL ,
    descripcionTipoDescuento VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE TipoDescuentoNomina ADD CONSTRAINT TipoDescuentoNomina_PK PRIMARY KEY ( idTipoDesc ) ;


CREATE TABLE TipoFactura
  (
    idTipoFactura     INTEGER NOT NULL ,
    nombreTipoFactura VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE TipoFactura ADD CONSTRAINT TipoFactura_PK PRIMARY KEY ( idTipoFactura ) ;


CREATE TABLE TipoMovimientos
  (
    idTipoMovimientos INTEGER NOT NULL ,
    nombreTipoMov     VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE TipoMovimientos ADD CONSTRAINT TipoMovimientos_PK PRIMARY KEY ( idTipoMovimientos ) ;


CREATE TABLE TipoParte
  (
    idTipoParte     INTEGER NOT NULL ,
    nombreTipoParte VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE TipoParte ADD CONSTRAINT TipoParte_PK PRIMARY KEY ( idTipoParte ) ;


CREATE TABLE TipoProceso
  (
    idTipoProceso     INTEGER NOT NULL ,
    nombreTipoProceso VARCHAR2 (25 CHAR) NOT NULL
  ) ;
ALTER TABLE TipoProceso ADD CONSTRAINT TipoProceso_PK PRIMARY KEY ( idTipoProceso ) ;


CREATE TABLE TipoTarjeta
  (
    idTipoTarjeta          INTEGER NOT NULL ,
    descripcionTipoTarjeta VARCHAR2 (50 CHAR)
  ) ;
ALTER TABLE TipoTarjeta ADD CONSTRAINT TipoTarjeta_PK PRIMARY KEY ( idTipoTarjeta ) ;


ALTER TABLE AcuerdoPago ADD CONSTRAINT AcuerdoPago_Banco_FK FOREIGN KEY ( idBanco ) REFERENCES Banco ( idBanco ) ;

ALTER TABLE AcuerdoPago ADD CONSTRAINT AcuerdoPago_Cotizacion_FK FOREIGN KEY ( idCotizacion ) REFERENCES Cotizacion ( idCotizacion ) ;

ALTER TABLE AcuerdoPago ADD CONSTRAINT AcuerdoPago_GrupoFinanciero_FK FOREIGN KEY ( idGrupoFin ) REFERENCES GrupoFinanciero ( idGrupo ) ;

ALTER TABLE AcuerdoPago ADD CONSTRAINT AcuerdoPago_ModalidadDePago_FK FOREIGN KEY ( idModalidadDePago ) REFERENCES ModalidadDePago ( idModalidad ) ;

ALTER TABLE AcuerdoPago ADD CONSTRAINT AcuerdoPago_TipoTarjeta_FK FOREIGN KEY ( idTipoTarjeta ) REFERENCES TipoTarjeta ( idTipoTarjeta ) ;

ALTER TABLE AutoCaracteristica ADD CONSTRAINT AutoCaracFK FOREIGN KEY ( idCaracteristica ) REFERENCES Caracteristica ( idCarac ) ;

ALTER TABLE Capacitacion ADD CONSTRAINT Capacitacion_Asistente_FK FOREIGN KEY ( dAsistente ) REFERENCES AsistenteCapacitacion ( idAsistente ) ;

ALTER TABLE Capacitacion ADD CONSTRAINT Capacitacion_Empleado_FK FOREIGN KEY ( idCapacitador ) REFERENCES Empleado ( idEmpleado ) ;

ALTER TABLE Caracteristica ADD CONSTRAINT CaracPadre_FK FOREIGN KEY ( idCaracPadre ) REFERENCES Caracteristica ( idCarac ) ;

ALTER TABLE AutoCaracteristica ADD CONSTRAINT Caracteristica_Auto_FK FOREIGN KEY ( idAuto ) REFERENCES Auto ( vim ) ;

ALTER TABLE Contacto ADD CONSTRAINT Contacto_Cliente_FK FOREIGN KEY ( idCliente ) REFERENCES Cliente ( idCliente ) ;

ALTER TABLE Contacto ADD CONSTRAINT Contacto_TipoContacto_FK FOREIGN KEY ( idTipoContacto ) REFERENCES TipoContacto ( idTipoContacto ) ;

ALTER TABLE Cotizacion ADD CONSTRAINT Cotizacion_Cliente_FK FOREIGN KEY ( idCliente ) REFERENCES Cliente ( idCliente ) ;

ALTER TABLE Cotizacion ADD CONSTRAINT Cotizacion_Empleado_FK FOREIGN KEY ( idEmpleado ) REFERENCES Empleado ( idEmpleado ) ;

ALTER TABLE DescuentoPago ADD CONSTRAINT DescPagoEmpleado_FK FOREIGN KEY ( idPagoEmpleado ) REFERENCES PagoEmpleado ( idPagoEmpleado ) ;

ALTER TABLE DescuentoPago ADD CONSTRAINT DescTipoDescNomina_FK FOREIGN KEY ( idTipoDescuento ) REFERENCES TipoDescuentoNomina ( idTipoDesc ) ;

ALTER TABLE DetalleFactura ADD CONSTRAINT DetalleFactura_AcuerdoPago_FK FOREIGN KEY ( idAcuerdoPago, idCotizacion ) REFERENCES AcuerdoPago ( idAcuerdoPago, idCotizacion ) ;

ALTER TABLE DetalleFactura ADD CONSTRAINT DetalleFactura_Factura_FK FOREIGN KEY ( idFactura ) REFERENCES Factura ( idFactura ) ;

ALTER TABLE DetalleCotizacion ADD CONSTRAINT Detalle_CotizacionFK FOREIGN KEY ( idCotizacion ) REFERENCES Cotizacion ( idCotizacion ) ;

ALTER TABLE Empleado ADD CONSTRAINT Empleado_Cargo_FK FOREIGN KEY ( idCargo ) REFERENCES Cargo ( idCargo ) ;

ALTER TABLE Empleado ADD CONSTRAINT Empleado_Evaluacion_FK FOREIGN KEY ( idEvaluador ) REFERENCES Evaluacion ( idEvaluacion ) ;

ALTER TABLE Empleado ADD CONSTRAINT Empleado_Region_FK FOREIGN KEY ( idRegion ) REFERENCES Region ( idRegion ) ;

ALTER TABLE Factura ADD CONSTRAINT Factura_Cliente_FK FOREIGN KEY ( idCliente ) REFERENCES Cliente ( idCliente ) ;

ALTER TABLE Factura ADD CONSTRAINT Factura_Cotizacion_FK FOREIGN KEY ( idCotizacion ) REFERENCES Cotizacion ( idCotizacion ) ;

ALTER TABLE Factura ADD CONSTRAINT Factura_Empleado_FK FOREIGN KEY ( idEmpleado ) REFERENCES Empleado ( idEmpleado ) ;

ALTER TABLE Factura ADD CONSTRAINT Factura_Proveedor_FK FOREIGN KEY ( idProveedor ) REFERENCES Proveedor ( idProveedor ) ;

ALTER TABLE Factura ADD CONSTRAINT Factura_TipoFactura_FK FOREIGN KEY ( idTipoFactura ) REFERENCES TipoFactura ( idTipoFactura ) ;

ALTER TABLE Garantia ADD CONSTRAINT Garantia_Registro_FK FOREIGN KEY ( Registro_idRegistro ) REFERENCES Registro ( idRegistro ) ;

ALTER TABLE HistoPrecioParte ADD CONSTRAINT HistoPrecioParte_Parte_FK FOREIGN KEY ( idParte ) REFERENCES Parte ( idParte ) ;

ALTER TABLE HistoPreciosAuto ADD CONSTRAINT HistoPreciosAuto_Auto_FK FOREIGN KEY ( idAuto ) REFERENCES Auto ( vim ) ;

ALTER TABLE HistoricoPreciosReg ADD CONSTRAINT HistoricoPreciosReg_FK FOREIGN KEY ( idRegistro ) REFERENCES Registro ( idRegistro ) ;

ALTER TABLE PagoEmpleado ADD CONSTRAINT PagoEmpleado_Empleado_FK FOREIGN KEY ( idEmpleado ) REFERENCES Empleado ( idEmpleado ) ;

ALTER TABLE ParteAuto ADD CONSTRAINT ParteAuto_Auto_FK FOREIGN KEY ( idAuto ) REFERENCES Auto ( vim ) ;

ALTER TABLE ParteAuto ADD CONSTRAINT ParteAuto_Parte_FK FOREIGN KEY ( idParte ) REFERENCES Parte ( idParte ) ;

ALTER TABLE Parte ADD CONSTRAINT Parte_TipoParte_FK FOREIGN KEY ( idTipoParte ) REFERENCES TipoParte ( idTipoParte ) ;

ALTER TABLE Proceso ADD CONSTRAINT Proceso_Cotizacion_FK FOREIGN KEY ( idCotizacion ) REFERENCES Cotizacion ( idCotizacion ) ;

ALTER TABLE Proceso ADD CONSTRAINT Proceso_TipoProceso_FK FOREIGN KEY ( idTipoProceso ) REFERENCES TipoProceso ( idTipoProceso ) ;

ALTER TABLE Registro ADD CONSTRAINT Registro_Aseguradora_FK FOREIGN KEY ( idAseguradora ) REFERENCES Aseguradora ( idAseguradora ) ;

ALTER TABLE Registro ADD CONSTRAINT Registro_Asesor_FK FOREIGN KEY ( idAsesor ) REFERENCES Empleado ( idEmpleado ) ;

ALTER TABLE Registro ADD CONSTRAINT Registro_Cotizacion_FK FOREIGN KEY ( idCotizacion ) REFERENCES Cotizacion ( idCotizacion ) ;

ALTER TABLE Registro ADD CONSTRAINT Registro_Mensajero_FK FOREIGN KEY ( idMensajero ) REFERENCES Empleado ( idEmpleado ) ;

ALTER TABLE Registro ADD CONSTRAINT Registro_TIpoRegistro_FK FOREIGN KEY ( idTipoRegistro ) REFERENCES TIpoRegistro ( idTipoRegistro ) ;

ALTER TABLE RespRecursoOfi ADD CONSTRAINT Resp_Empleado_FK FOREIGN KEY ( idEmpleado ) REFERENCES Empleado ( idEmpleado ) ;

ALTER TABLE RespRecursoOfi ADD CONSTRAINT Resp_RecursoOficina_FK FOREIGN KEY ( idRecurso ) REFERENCES RecursoOficina ( idRecurso ) ;

ALTER TABLE StockAutos ADD CONSTRAINT StockAutos_Auto_FK FOREIGN KEY ( idAuto ) REFERENCES Auto ( vim ) ;

ALTER TABLE StockAutos ADD CONSTRAINT StockAutos_DetalleFactura_FK FOREIGN KEY ( idDetalleFactura, idDocRespaldo ) REFERENCES DetalleFactura ( idDetalleFact, idFactura ) ;

ALTER TABLE StockAutos ADD CONSTRAINT StockAutos_EstadoStock_FK FOREIGN KEY ( idEstadoStock ) REFERENCES EstadoStock ( idEstadoStock ) ;

ALTER TABLE StockAutos ADD CONSTRAINT StockAutos_TipoMovimientos_FK FOREIGN KEY ( idTipoMovimientos ) REFERENCES TipoMovimientos ( idTipoMovimientos ) ;

ALTER TABLE StockParte ADD CONSTRAINT StockParte_DetalleFactura_FK FOREIGN KEY ( idDetalleFactura, idFactura ) REFERENCES DetalleFactura ( idDetalleFact, idFactura ) ;

ALTER TABLE StockParte ADD CONSTRAINT StockParte_EstadoStockParte_FK FOREIGN KEY ( idEstadoStockParte ) REFERENCES EstadoStockParte ( idEstadoStockParte ) ;

ALTER TABLE StockParte ADD CONSTRAINT StockParte_Parte_FK FOREIGN KEY ( idParte ) REFERENCES Parte ( idParte ) ;

ALTER TABLE StockParte ADD CONSTRAINT StockParte_TipoMovimientos_FK FOREIGN KEY ( idTipoMovimientos ) REFERENCES TipoMovimientos ( idTipoMovimientos ) ;

ALTER TABLE Caracteristica ADD CONSTRAINT TipoCarac_FK FOREIGN KEY ( idTipoCarac ) REFERENCES TipoCaracteristica ( idTipoCaracteristica ) ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            46
-- CREATE INDEX                             3
-- ALTER TABLE                            100
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
